package:
  name: gtkwave
  version: 3.3.68

source:
  fn: gtkwave-3.3.68.tar.gz
  url: http://gtkwave.sourceforge.net/gtkwave-3.3.68.tar.gz

  patches:
    - nosplash.patch   # bypass annoying splash screen

build:
  number: 0

# Requires gtk2 and pkg-config from some other platform package manager
requirements:
  build:
    - zlib
  run:
    - zlib

about:
  home: http://gtkwave.sourceforge.net/
