package:
  name: iverilog
  version: 0.9.7

source:
  git_url: https://github.com/steveicarus/iverilog.git
  git_tag: v0_9_7

build:
  number: 1
  binary_relocation: true
  binary_has_prefix_files:
    - bin/iverilog
    - bin/vvp

about:
  home: http://iverilog.icarus.com/home
