package:
  name: iverilog
  version: 10.0

source:
  git_url: https://github.com/steveicarus/iverilog.git
  git_tag: v10_0

build:
  number: 0
  binary_relocation: true
  binary_has_prefix_files:
    - bin/iverilog
    - bin/vvp

about:
  home: http://iverilog.icarus.com/home
