package:
  name: srec2bin
  version: 0.1

source:
  git_url: https://github.com/tfors/srec2bin.git
  git_tag: v0.1

build:
  number: 0

about:
        home: http://www.dragonwins.com/domains/getteched/rfid/srec2bin/index.htm
